declare const styles: {
  readonly "cardLabel": string;
  readonly "due": string;
  readonly "eyebrow": string;
  readonly "fieldLabel": string;
  readonly "headingIcon": string;
  readonly "highlight": string;
  readonly "homeScreen": string;
  readonly "insightCard": string;
  readonly "metricItem": string;
  readonly "metricName": string;
  readonly "metricValue": string;
  readonly "metricsGrid": string;
  readonly "metricsRow": string;
  readonly "overviewCard": string;
  readonly "pageHeading": string;
  readonly "progressBg": string;
  readonly "progressCenter": string;
  readonly "progressCircle": string;
  readonly "progressCircleContainer": string;
  readonly "progressLabel": string;
  readonly "progressNumber": string;
  readonly "progressRing": string;
  readonly "progressSvg": string;
  readonly "selectorCard": string;
  readonly "selectorCopy": string;
  readonly "startButton": string;
};
export = styles;

